trigger:
  branches:
    include:
      - main
  paths:
    include:
      - htmlapp/**
      - pythonapp/**
      - nginxproxy/**
      - healthcheck/**

pool:
  vmImage: ubuntu-latest

variables:
  ACR_NAME: myacrramraja
  AKS_CLUSTER: myAKSCluster
  RESOURCE_GROUP: myDevOpsRG

stages:
- stage: Deploy
  jobs:
  - job: DeployToAKS
    displayName: 'Deploy All Apps to AKS'
    steps:
    - checkout: self

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'my-azure-connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "📥 Getting AKS credentials..."
          az aks get-credentials --resource-group $(RESOURCE_GROUP) --name $(AKS_CLUSTER) --overwrite-existing

          echo "🚀 Deploying HTML App..."
          kubectl apply -f htmlapp-deployment.yaml
          kubectl apply -f htmlapp-service.yaml

          echo "🚀 Deploying Python App..."
          kubectl apply -f pythonapp/pythonapp-deployment.yaml
          kubectl apply -f pythonapp/pythonapp-service.yaml

          echo "🚀 Deploying NGINX Proxy..."
          kubectl apply -f nginxproxy/nginxproxy-deployment.yaml
          kubectl apply -f nginxproxy/nginxproxy-service.yaml

          echo "🚀 Deploying HealthCheck App..."
          kubectl apply -f healthcheck/healthcheck-deployment.yaml
          kubectl apply -f healthcheck/healthcheck-service.yaml
